version: "3.8"
services:
  webapp:
    image: mcr.microsoft.com/dotnet/sdk:2.1
    #depends_on: mariadb
  mariadb:
    build: 
      context: .
      dockerfile: Dockerfile.mariadb
    expose:
      - 3306:3306
