version: "3.8"
services:
  webapp:
    build: 
      context: .
      dockerfile: docker/liftpass/Dockerfile      
    depends_on: 
      - mariadb
    ports:
      - "8080:5000"
    
          
  mariadb:
    build: 
      context: .
      dockerfile: docker/mariadb/Dockerfile
    ports:
      - "3306:3306"
